ALTER TABLE course_prices
  ALTER COLUMN currency SET DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS regular_price_2 NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_percent_2 NUMERIC(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS final_price_2 NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_scraped_price_2 NUMERIC(10,2);

UPDATE course_prices
SET currency = 'USD'
WHERE currency IS NULL OR currency = 'GBP';
